[[redirects]]
from = "/visiter-amsterdam-printemps-2019"
to = "/visiter-amsterdam-au-printemps"

[[redirects]]
from = "/vie-dexpat-4-les-jours-feries"
to = "/les-jours-feries-pays-bas"

[context.production.environment]
GA_TRACKING_ID="UA-34357788-4"
STORYBLOK_API_KEY="oVQID07p9fiFPOrWDCg3rgtt"
STORYBLOK_VERSION="published"
SITE_URL="https://adeux-cestmieux.com"

[context.develop.environment]
GA_TRACKING_ID="UA-34357788-6"
STORYBLOK_API_KEY="Dq9tMhBqMlJxD2kIdqbrJgtt"
STORYBLOK_VERSION="draft"
SITE_URL="https://develop--adeux-cestmieux.netlify.com"

[context.landing-page.environment]
GA_TRACKING_ID="UA-34357788-6"
SITE_URL="https://develop--adeux-cestmieux.netlify.com"