[context.production.environment]
GA_TRACKING_ID="UA-34357788-6"
SITE_URL="https://adeux-cestmieux.netlify.com"

[context.develop.environment]
GA_TRACKING_ID="UA-34357788-6"
SITE_URL="https://develop--adeux-cestmieux.netlify.com"